wandb_version: 1

activation:
  value: identity
batch_size:
  value: 16
beta:
  value: 0.8543785658851888
beta1:
  value: 0.9012793723993064
beta2:
  value: 0.7208498261421964
dataset:
  value: mnist
epochs:
  value: 5
epsilon:
  value: 1.0e-08
hidden_size:
  value: 64
learning_rate:
  value: 0.0003
loss:
  value: cross_entropy
momentum:
  value: 0.5351920839766872
num_layers:
  value: 4
optimizer:
  value: nag
output_activation:
  value: softmax
weight_decay:
  value: 0
weight_init:
  value: xavier
