program: train.py
method: bayes
metric:
  name: validation_loss
  goal: minimize
parameters:
  dataset:
    values: ["fashion_mnist", "mnist"]
  epochs:
    values: [5, 10 ,20]
  batch_size:
    values: [16,32,64,128]
  loss: 
    values: ["cross_entropy", "mean_squared_error"]
  optimizer: 
    values: ["sgd", "momentum", "nag", "rmsprop", "adam", "nadam"]
  learning_rate: 
    values: [0.001, 0.0001,0.0002,0.0003]
  momentum:
    min: 0.5
    max: 0.999
  beta:
    min: 0.5
    max: 0.999
  beta1:
    min: 0.5
    max: 0.999
  beta2:
    min: 0.5
    max: 0.999
  epsilon:
    value: 0.00000001
  weight_decay: 
    values : [0,0.0005]
  weight_ini:
    values: ['random','xavier']
  num_layers: 
    values: [3,4,5]
  hidden_size: 
    values: [16,32,64,128,256]
  activations:
    values: ["identity", "sigmoid", "tanh", "ReLU"]
  output_activation:
    value: "softmax"
  
  