wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1677593816.299474
    t:
      1:
      - 2
      - 3
      - 49
      - 51
      - 55
      2:
      - 2
      - 3
      - 49
      - 51
      - 55
      3:
      - 2
      - 23
      4: 3.10.10
      5: 0.13.10
      8:
      - 1
      - 4
      - 5
