wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 16
beta:
  value: 0.5006697753795781
beta1:
  value: 0.6921110758436011
beta2:
  value: 0.7394547196564489
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: 64
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
momentum:
  value: 0.8669285843343926
num_layers:
  value: 3
optimizer:
  value: nag
output_activation:
  value: softmax
weight_decay:
  value: 0
weight_init:
  value: random
