wandb_version: 1

activations:
  value: identity
batch_size:
  value: 32
beta:
  value: 0.94186008088874
beta1:
  value: 0.9656967956175062
beta2:
  value: 0.843317279576402
dataset:
  value: mnist
epochs:
  value: 20
epsilon:
  value: 1.0e-08
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
momentum:
  value: 0.8760073883701298
num_layers:
  value: 5
optimizer:
  value: nag
output_activation:
  value: softmax
weight_decay:
  value: 0.0005
weight_init:
  value: random
