wandb_version: 1

activations:
  value: identity
batch_size:
  value: 32
beta:
  value: 0.6999890450135271
beta1:
  value: 0.5946113229127674
beta2:
  value: 0.8016040225052219
dataset:
  value: mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: 16
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
momentum:
  value: 0.5038997207000697
num_layers:
  value: 4
optimizer:
  value: nag
output_activation:
  value: softmax
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
