wandb_version: 1

activations:
  value: ReLU
batch_size:
  value: 16
beta:
  value: 0.8414913281298626
beta1:
  value: 0.8611862903770116
beta2:
  value: 0.6574622678957586
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
momentum:
  value: 0.652803499905044
num_layers:
  value: 3
optimizer:
  value: nag
output_activation:
  value: softmax
weight_decay:
  value: 0.0005
weight_init:
  value: random
