wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 32
beta:
  value: 0.7625902210769226
beta1:
  value: 0.7995683075126367
beta2:
  value: 0.8463079688639952
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: 32
learning_rate:
  value: 0.0003
loss:
  value: cross_entropy
momentum:
  value: 0.6352768706800644
num_layers:
  value: 4
optimizer:
  value: nag
output_activation:
  value: softmax
weight_decay:
  value: 0
weight_init:
  value: random
