wandb_version: 1

activations:
  value: ReLU
batch_size:
  value: 128
beta:
  value: 0.6265077423707206
beta1:
  value: 0.7181921785230421
beta2:
  value: 0.8336985424407977
dataset:
  value: mnist
epochs:
  value: 20
epsilon:
  value: 1.0e-08
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
momentum:
  value: 0.6238268685824072
num_layers:
  value: 3
optimizer:
  value: nag
output_activation:
  value: softmax
weight_decay:
  value: 0.0005
weight_init:
  value: random
