wandb_version: 1

activations:
  value: identity
batch_size:
  value: 16
beta:
  value: 0.9237309519648732
beta1:
  value: 0.973312334975585
beta2:
  value: 0.702778093122777
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: 16
learning_rate:
  value: 0.0003
loss:
  value: mean_squared_error
momentum:
  value: 0.9934921184835854
num_layers:
  value: 5
optimizer:
  value: nadam
output_activation:
  value: softmax
weight_decay:
  value: 0
weight_init:
  value: xavier
