wandb_version: 1

activations:
  value: ReLU
batch_size:
  value: 16
beta:
  value: 0.5190602138380651
beta1:
  value: 0.859321348343572
beta2:
  value: 0.7545065976732506
dataset:
  value: mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
momentum:
  value: 0.7876963228980194
num_layers:
  value: 4
optimizer:
  value: rmsprop
output_activation:
  value: softmax
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
