wandb_version: 1

activations:
  value: identity
batch_size:
  value: 128
beta:
  value: 0.7050502113760276
beta1:
  value: 0.5023491998988422
beta2:
  value: 0.6767015037888828
dataset:
  value: mnist
epochs:
  value: 5
epsilon:
  value: 1.0e-08
hidden_size:
  value: 16
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
momentum:
  value: 0.8985061452799111
num_layers:
  value: 3
optimizer:
  value: nag
output_activation:
  value: softmax
weight_decay:
  value: 0
weight_init:
  value: random
