wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 128
beta:
  value: 0.5891998716917133
beta1:
  value: 0.9440075349799362
beta2:
  value: 0.5262339793348987
dataset:
  value: fashion_mnist
epochs:
  value: 5
epsilon:
  value: 1.0e-08
hidden_size:
  value: 64
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
momentum:
  value: 0.5367760469841059
num_layers:
  value: 4
optimizer:
  value: sgd
output_activation:
  value: softmax
weight_decay:
  value: 0.0005
weight_init:
  value: random
