wandb_version: 1

activations:
  value: tanh
batch_size:
  value: 128
beta:
  value: 0.9937069010546676
beta1:
  value: 0.7273352615628194
beta2:
  value: 0.652918515395762
dataset:
  value: mnist
epochs:
  value: 20
epsilon:
  value: 1.0e-08
hidden_size:
  value: 32
learning_rate:
  value: 0.0003
loss:
  value: cross_entropy
momentum:
  value: 0.7148158518999709
num_layers:
  value: 5
optimizer:
  value: nadam
output_activation:
  value: softmax
weight_decay:
  value: 0
weight_init:
  value: xavier
