wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 64
beta:
  value: 0.6735775802380016
beta1:
  value: 0.6214904810461633
beta2:
  value: 0.7954747356527818
dataset:
  value: mnist
epochs:
  value: 20
epsilon:
  value: 1.0e-08
hidden_size:
  value: 128
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
momentum:
  value: 0.644523077934158
num_layers:
  value: 3
optimizer:
  value: momentum
output_activation:
  value: softmax
weight_decay:
  value: 0
weight_init:
  value: random
