wandb_version: 1

activations:
  value: sigmoid
batch_size:
  value: 128
beta:
  value: 0.6165313379092684
beta1:
  value: 0.7084295953745073
beta2:
  value: 0.8655025669026131
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: 64
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
momentum:
  value: 0.5795883179302153
num_layers:
  value: 4
optimizer:
  value: adam
output_activation:
  value: softmax
weight_decay:
  value: 0
weight_init:
  value: random
