wandb_version: 1

activations:
  value: identity
batch_size:
  value: 32
beta:
  value: 0.6484079699990197
beta1:
  value: 0.9094951134858776
beta2:
  value: 0.5037092235401289
dataset:
  value: mnist
epochs:
  value: 5
epsilon:
  value: 1.0e-08
hidden_size:
  value: 256
learning_rate:
  value: 0.0003
loss:
  value: mean_squared_error
momentum:
  value: 0.8153676122017025
num_layers:
  value: 5
optimizer:
  value: momentum
output_activation:
  value: softmax
weight_decay:
  value: 0
weight_init:
  value: xavier
