wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1678529327.093558
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      - 24
      - 37
      4: 3.10.10
      5: 0.13.10
      8:
      - 4
      - 5
activations:
  desc: null
  value: identity
batch_size:
  desc: null
  value: 32
beta:
  desc: null
  value: 0.6484079699990197
beta1:
  desc: null
  value: 0.9094951134858776
beta2:
  desc: null
  value: 0.5037092235401289
dataset:
  desc: null
  value: mnist
epochs:
  desc: null
  value: 5
epsilon:
  desc: null
  value: 1.0e-08
hidden_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.0003
loss:
  desc: null
  value: mean_squared_error
momentum:
  desc: null
  value: 0.8153676122017025
num_layers:
  desc: null
  value: 5
optimizer:
  desc: null
  value: momentum
output_activation:
  desc: null
  value: softmax
weight_decay:
  desc: null
  value: 0
weight_init:
  desc: null
  value: xavier
