wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
beta:
  value: 0.7756623221671055
beta1:
  value: 0.7912446366933534
beta2:
  value: 0.7977300326812835
dataset:
  value: fashion_mnist
epochs:
  value: 5
epsilon:
  value: 1.0e-08
hidden_size:
  value: 32
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
momentum:
  value: 0.9569216376521988
num_layers:
  value: 3
optimizer:
  value: nadam
output_activation:
  value: softmax
weight_decay:
  value: 0.0005
weight_init:
  value: random
