wandb_version: 1

activation:
  value: identity
batch_size:
  value: 16
beta:
  value: 0.7593704224296726
beta1:
  value: 0.8546910741671794
beta2:
  value: 0.9178229082216012
dataset:
  value: fashion_mnist
epochs:
  value: 20
epsilon:
  value: 1.0e-08
hidden_size:
  value: 64
learning_rate:
  value: 0.0002
loss:
  value: cross_entropy
momentum:
  value: 0.5751081163798433
num_layers:
  value: 4
optimizer:
  value: momentum
output_activation:
  value: softmax
weight_decay:
  value: 0
weight_init:
  value: xavier
