wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
beta:
  value: 0.812180276482569
beta1:
  value: 0.743375734076317
beta2:
  value: 0.5035526462727477
dataset:
  value: mnist
epochs:
  value: 5
epsilon:
  value: 1.0e-08
hidden_size:
  value: 16
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
momentum:
  value: 0.5702691413050186
num_layers:
  value: 3
optimizer:
  value: nadam
output_activation:
  value: softmax
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
