wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
beta:
  value: 0.7788731623762359
beta1:
  value: 0.623447915293714
beta2:
  value: 0.5896332217796969
dataset:
  value: mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: 32
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
momentum:
  value: 0.5714413201677575
num_layers:
  value: 5
optimizer:
  value: momentum
output_activation:
  value: softmax
weight_decay:
  value: 0
weight_init:
  value: random
