wandb_version: 1

activation:
  value: identity
batch_size:
  value: 16
beta:
  value: 0.7769192025984464
beta1:
  value: 0.7644305839614141
beta2:
  value: 0.5348020821024382
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: 256
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
momentum:
  value: 0.5998188903240299
num_layers:
  value: 4
optimizer:
  value: sgd
output_activation:
  value: softmax
weight_decay:
  value: 0
weight_init:
  value: random
