wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 128
beta:
  value: 0.9513586521112742
beta1:
  value: 0.5407785891939594
beta2:
  value: 0.8057068194043194
dataset:
  value: fashion_mnist
epochs:
  value: 20
epsilon:
  value: 1.0e-08
hidden_size:
  value: 64
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
momentum:
  value: 0.8435650098646696
num_layers:
  value: 3
optimizer:
  value: momentum
output_activation:
  value: softmax
weight_decay:
  value: 0
weight_init:
  value: xavier
