wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1678529604.992991
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.10
      5: 0.13.10
      8:
      - 4
      - 5
activations:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 16
beta:
  desc: null
  value: 0.9939092105315256
beta1:
  desc: null
  value: 0.5555360163608835
beta2:
  desc: null
  value: 0.8129208467726916
dataset:
  desc: null
  value: mnist
epochs:
  desc: null
  value: 10
epsilon:
  desc: null
  value: 1.0e-08
hidden_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.0003
loss:
  desc: null
  value: cross_entropy
momentum:
  desc: null
  value: 0.5869557500622531
num_layers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: adam
output_activation:
  desc: null
  value: softmax
weight_decay:
  desc: null
  value: 0
weight_init:
  desc: null
  value: random
